{
  imports = [
    ./containers.nix
    ./documentation.nix
    ./emulation.nix
    ./fonts.nix
    ./home-manager.nix
    ./locale.nix
    ./nix-ld.nix
    ./nix.nix
    ./nixpkgs.nix
    ./storage.nix
    ./stylix.nix
    ./sudo.nix
    ./swap.nix
    ./timezone.nix
    ./yubikey.nix
  ];
}
