local map = vim.keymap.set

map('n', '<Leader><Leader>', '<Cmd>Pick files<CR>', { desc = 'Find files' })
map('n', '<Leader>.', '<Cmd>lua MiniFiles.open()<CR>', { desc = 'File explorer' })
map('n', '<Leader>,', '<Cmd>Pick buffers<CR>', { desc = 'Switch buffer' })
map('n', '<Leader>:', ':', { desc = 'Command mode' })
map('n', '<Leader>/', '<Cmd>Pick grep_live<CR>', { desc = 'Search project' })

map('n', '<Leader>bb', '<Cmd>Pick buffers<CR>', { desc = 'Switch buffer' })
map('n', '<Leader>bd', '<Cmd>lua MiniBufremove.delete()<CR>', { desc = 'Delete buffer' })
map('n', '<Leader>bD', '<Cmd>lua MiniBufremove.delete(0, true)<CR>', { desc = 'Force delete buffer' })
map('n', '<Leader>bn', '<Cmd>bnext<CR>', { desc = 'Next buffer' })
map('n', '<Leader>bp', '<Cmd>bprevious<CR>', { desc = 'Previous buffer' })
map('n', '<Leader>bN', '<Cmd>enew<CR>', { desc = 'New buffer' })
map('n', '<Leader>bs', '<Cmd>Pick buf_lines<CR>', { desc = 'Search in buffer' })

map('n', '<Leader>ff', '<Cmd>Pick files<CR>', { desc = 'Find file' })
map('n', '<Leader>fr', '<Cmd>Pick oldfiles<CR>', { desc = 'Recent files' })
map('n', '<Leader>fR', '<Cmd>Pick visit_paths<CR>', { desc = 'Recent paths (visits)' })
map('n', '<Leader>fs', '<Cmd>w<CR>', { desc = 'Save file' })
map('n', '<Leader>fS', '<Cmd>wa<CR>', { desc = 'Save all files' })
map('n', '<Leader>ft', '<Cmd>lua MiniFiles.open()<CR>', { desc = 'File tree' })
map('n', '<Leader>fe', '<Cmd>lua MiniFiles.open(vim.api.nvim_buf_get_name(0))<CR>', { desc = 'Find file in tree' })
map('n', '<Leader>fy', '<Cmd>let @+ = expand("%:p")<CR>', { desc = 'Yank file path' })

map('n', '<Leader>gg', '<Cmd>lua MiniGit.show_at_cursor()<CR>', { desc = 'Show git info' })
map('n', '<Leader>gd', '<Cmd>lua MiniDiff.toggle_overlay()<CR>', { desc = 'Toggle diff overlay' })
map('n', '<Leader>gD', '<Cmd>lua MiniDiff.toggle()<CR>', { desc = 'Toggle diff signs' })
map('n', '<Leader>gs', '<Cmd>Pick git_files<CR>', { desc = 'Git status' })
map('n', '<Leader>gc', '<Cmd>Pick git_commits<CR>', { desc = 'Git commits' })
map('n', '<Leader>gb', '<Cmd>Pick git_branches<CR>', { desc = 'Git branches' })
map('n', '<Leader>gh', '<Cmd>Pick git_hunks<CR>', { desc = 'Git hunks' })

map('n', '<Leader>hh', '<Cmd>Pick help<CR>', { desc = 'Help tags' })
map('n', '<Leader>hk', '<Cmd>Pick keymaps<CR>', { desc = 'Search keymaps' })
map('n', '<Leader>hm', '<Cmd>Pick commands<CR>', { desc = 'Search commands' })
map('n', '<Leader>hn', '<Cmd>lua MiniNotify.show_history()<CR>', { desc = 'Show notifications' })

map('n', '<Leader>pf', '<Cmd>Pick files<CR>', { desc = 'Find file in project' })
map('n', '<Leader>pg', '<Cmd>Pick grep_live<CR>', { desc = 'Grep in project' })
map('n', '<Leader>ps', '<Cmd>Pick grep pattern="<cword>"<CR>', { desc = 'Search word in project' })

map('n', '<Leader>qq', '<Cmd>qa<CR>', { desc = 'Quit all' })
map('n', '<Leader>qQ', '<Cmd>qa!<CR>', { desc = 'Quit all force' })
map('n', '<Leader>qs', '<Cmd>lua MiniSessions.select("write")<CR>', { desc = 'Save session' })
map('n', '<Leader>ql', '<Cmd>lua MiniSessions.select("read")<CR>', { desc = 'Load session' })

map('n', '<Leader>ss', '<Cmd>Pick grep_live<CR>', { desc = 'Search (live grep)' })
map('n', '<Leader>sw', '<Cmd>Pick grep pattern="<cword>"<CR>', { desc = 'Search word under cursor' })
map('n', '<Leader>sb', '<Cmd>Pick buf_lines<CR>', { desc = 'Search in buffer' })
map('n', '<Leader>sr', '<Cmd>Pick resume<CR>', { desc = 'Resume last search' })

map('n', '<Leader>tw', '<Cmd>set wrap!<CR>', { desc = 'Toggle wrap' })
map('n', '<Leader>tn', '<Cmd>set number!<CR>', { desc = 'Toggle line numbers' })
map('n', '<Leader>tr', '<Cmd>set relativenumber!<CR>', { desc = 'Toggle relative numbers' })
map('n', '<Leader>ts', '<Cmd>set spell!<CR>', { desc = 'Toggle spell check' })
map('n', '<Leader>td', '<Cmd>lua MiniDiff.toggle()<CR>', { desc = 'Toggle diff signs' })
map('n', '<Leader>tm', '<Cmd>lua MiniMap.toggle()<CR>', { desc = 'Toggle minimap' })

map('n', '<Leader>ww', '<C-w>w', { desc = 'Other window' })
map('n', '<Leader>wd', '<C-w>c', { desc = 'Delete window' })
map('n', '<Leader>w-', '<C-w>s', { desc = 'Split horizontal' })
map('n', '<Leader>w/', '<C-w>v', { desc = 'Split vertical' })
map('n', '<Leader>wh', '<C-w>h', { desc = 'Move to left window' })
map('n', '<Leader>wj', '<C-w>j', { desc = 'Move to window below' })
map('n', '<Leader>wk', '<C-w>k', { desc = 'Move to window above' })
map('n', '<Leader>wl', '<C-w>l', { desc = 'Move to right window' })
map('n', '<Leader>wH', '<C-w>H', { desc = 'Move window left' })
map('n', '<Leader>wJ', '<C-w>J', { desc = 'Move window down' })
map('n', '<Leader>wK', '<C-w>K', { desc = 'Move window up' })
map('n', '<Leader>wL', '<C-w>L', { desc = 'Move window right' })
map('n', '<Leader>w=', '<C-w>=', { desc = 'Balance windows' })

map('n', '<Leader>xw', '<Cmd>lua MiniTrailspace.trim()<CR>', { desc = 'Trim trailing whitespace' })
map('n', '<Leader>xj', '<Cmd>lua MiniSplitjoin.toggle()<CR>', { desc = 'Split/join' })
