{ lib, config, ... }:
let
  eg = config.psyclyx.egregore;
in
{
  imports = [ ./dhcp.nix ];

  networking.hostName = "iyr";

  # The gateway mechanism — LAN/WAN interfaces, the transit DHCP
  # clients, CAKE shaping on the uplink. The routed segments, MACs,
  # transit VLAN and initrd VLANs come from the projection
  # (derived/gateway.nix); only the box's own wiring is here.
  psyclyx.nixos.network = {
    gateway = {
      enable = true;
      lanInterface = "enp1s0";
      wanInterface = "enp3s0";
      lanAddress = "10.0.0.11/24"; # untagged trunk (legacy setup VLAN 1)
      initrd.kernelModules = [ "8021q" "igc" ];
      transitDhcpV6.duidRawData = "e7:13:f8:92:37:c5:be:76";
      # Comcast/Xfinity DHCP sends option-121 classless static routes
      # with no 0.0.0.0/0, which (per RFC 3442) suppresses the option-3
      # gateway and leaves enp3s0.250 with no default route. Ignore
      # option 121 so networkd installs the gateway as the main-table
      # default — the always-on IPv4 fallback the Google Fiber failover
      # falls back to.
      transitDhcpV4.useRoutes = false;
    };
    cake-qos = {
      enable = true;
      interface = "enp3s0.${toString eg.conventions.transitVlan}";
      # Xfinity apartment uplink — symmetric 2.2 Gbps provisioned.
      # Min kept low for graceful autorate degradation; max gives small
      # headroom past nominal.
      download = { min = 1400000; base = 2200000; max = 2280000; };
      upload = { min = 1400000; base = 2200000; max = 2280000; };
    };
  };

  systemd.network.networks."31-enp3s0.${toString eg.conventions.transitVlan}".linkConfig.MTUBytes = 1500;

  # Google Fiber (VLAN 251) — the primary IPv4 uplink. The GF ONT lands
  # on idf-dist01 sfp4 and is trunked to iyr tagged alongside Xfinity
  # (250) via mdf-brk01 port5. GF carries IPv4 only: IPv6 stays entirely
  # on Xfinity (VLAN 250), which keeps its DHCPv6-PD /60 that numbers
  # every internal VLAN, so there's no renumbering on failover.
  #
  # GF's default route is pinned to a dedicated table (251) via
  # dhcpV4Config.RouteTable and never touches the main table. The
  # wan-failover watchdog (below) is what actually steers internet
  # traffic onto it — while GF is healthy it installs policy rules that
  # prefer table 251, and it removes them (falling back to Xfinity's
  # main-table default) whenever GF's link or internet drops. Xfinity's
  # unit (generated by derived/gateway.nix) is unchanged: it remains the
  # main-table default and thus the always-on IPv4 fallback.
  #
  # The oif rule keeps GF reachable for source-bound diagnostics
  # (`ping -I enp3s0.251 1.1.1.1`) and, crucially, for the watchdog's
  # own probes — device-bound sockets resolve via table 251 through it,
  # so the probe tests GF's real path regardless of the current default.
  #
  # Firewall posture is the shared `wan` zone (enp3s0.251 is added there
  # in the iyr host entity): input drop + ICMP + DHCP-client only. The
  # VLAN netdev + enp3s0 parent-list wiring come from the interfaces
  # module; only the L3/DHCP unit is hand-written (the generic gateway
  # module's dhcp path installs into the main table, which we don't want
  # for the primary since the watchdog owns the main-table selection).
  psyclyx.nixos.network.interfaces.vlans."enp3s0.251" = { id = 251; parent = "enp3s0"; };
  systemd.network.networks."31-enp3s0.251" = {
    matchConfig.Name = "enp3s0.251";
    networkConfig = {
      DHCP = "ipv4";
      IPv6AcceptRA = false;
    };
    dhcpV4Config = {
      RouteTable = 251;
      UseDNS = false;
      UseNTP = false;
      UseHostname = false;
      ClientIdentifier = "mac";
    };
    routingPolicyRules = [{
      OutgoingInterface = "enp3s0.251";
      Family = "ipv4";
      Table = 251;
      Priority = 251;
    }];
    linkConfig = {
      MTUBytes = 1500;
      RequiredForOnline = "no";
    };
  };

  # L2-only listener VLANs (lab, storage) on enp1s0 come from
  # derived/l2-listeners.nix; parent-unit VLAN aggregation is done by
  # network/interfaces.nix so gateway + listener children all hang off
  # the same enp1s0 unit automatically.

  # Tang server config (bind + ACL) comes from derived/tang.nix, driven
  # by the iyr-tang egregore entity (configs/egregore/trust-root.nix).

  # node + smartctl exporter listen addresses come from
  # derived/monitoring.nix (driven by the host entity's exporters
  # declaration). snmp is iyr-specific and stays local.
  services.prometheus.exporters.snmp.listenAddress = "127.0.0.1";
  services.prometheus.listenAddress = "127.0.0.1";

  psyclyx.nixos = {
    boot.initrd-ssh.enable = true;

    filesystems.layouts.bcachefs-pool = {
      enable = true;
      UUID = {
        root = "0b6d93c8-c6d3-4243-9413-25543a093c65";
        boot = "0289-61AC";
      };
    };

    hardware = {
      cpu.intel.enable = true;
      gpu.intel.enable = true;
    };

    network = {
      # Gateway config (lanInterface/wanInterface/MACs/initrdVlans/
      # DHCPv6 DUID/CAKE QoS rates) comes from iyr's host.gateway in
      # egregore via derived/gateway.nix. CAKE stays on Xfinity (VLAN
      # 250) — Google Fiber (the primary, VLAN 251) is left unshaped.

      # Prefer Google Fiber (enp3s0.251, default route in table 251),
      # falling back to Xfinity's main-table default when GF is
      # unhealthy. See the enp3s0.251 unit above and wan-failover.nix.
      wan-failover = {
        enable = true;
        primaryInterface = "enp3s0.251";
        primaryTable = 251;
      };

      dhcp-ddns.enable = true;

      dns = {
        client.enable = true;
        zones = {
          enable = true;
          siteZone = {
            enable = true;
            # main first (iyr/sigil), then lab so lab hosts (no main
            # address since they live behind the L3 switch) still land
            # at <host>.apt.psyclyx.net via their lab-VLAN IP. Storage
            # stays out of the site apex (it's iSCSI-only, no off-rack
            # clients should resolve a host to its storage IP).
            networks = [ "main" "lab" ];
          };
        };
        resolver = {
          enable = true;
          # Listen list (gateway addresses + L2 listener addresses +
          # vpn + ::) comes from derived/dns-resolver.nix. Adding the
          # untagged trunk IP here because it's not modeled in egregore.
          interfaces = [ "10.0.0.11" ];
          accessControl = [
            "10.0.0.0/8 allow"
            "${eg.ipv6UlaPrefix}::/48 allow"
            "fe80::/10 allow"
            "::1/128 allow"
          ];
          # Cross-site forwarding auto-derived from egregore site refs.dns
          # by derived/dns-forwarding.nix.
        };
      };

      # Firewall. The zone→interface map and the forward matrix are
      # derived from the fleet (derived/firewall-policy.nix): zones from
      # `network.zone` + `host.interfaces`, forward rules from
      # `globals.policy`. The rest — extra interfaces for links that
      # aren't network entities, per-zone input policy, and NAT — is
      # this box's own wiring.
      firewall = {
        enable = true;
        zones = {
          # enp1s0 (untagged trunk parent) shares trust with main → the
          # lan zone. enp3s0.250/.251 are the WAN VLAN sub-ifaces
          # (transit isn't modeled as a network entity — no internal
          # subnet). .250 is Xfinity (IPv6 + IPv4 fallback), .251 is
          # Google Fiber (the primary IPv4 uplink); both share the WAN
          # drop+ICMP+DHCP-client posture.
          lan.interfaces = [ "enp1s0" ];
          wan.interfaces = [ "enp3s0.250" "enp3s0.251" ];
        };
        input = {
          # Internal zones: trusted.
          lan.policy = "accept";
          infra.policy = "accept";
          storage.policy = "accept";
          lab-transit.policy = "accept";
          mgmt.policy = "accept";
          wg.policy = "accept";
          # Traffic mdf-agg01 hands us over the transit. Almost nothing
          # terminates here: iyr holds an address on every segment it
          # serves, so clients reach its services directly on their own
          # VLAN. What does arrive is relayed DHCP, which the switch
          # unicasts to iyr's transit address.
          core-transit = {
            policy = "drop";
            allowICMP = true;
            rules = [
              { "udp dport" = 67; comment = "DHCPv4 relay"; }
              { "udp dport" = 547; comment = "DHCPv6 relay"; }
            ];
          };
          # WAN: drop + specific allows. The TCP port is the SSH service
          # port.
          wan = {
            policy = "drop";
            allowICMP = true;
            allowedTCPPorts = [ 17891 ]; # ssh
            rules = [
              { "udp sport" = 67; "udp dport" = 68; comment = "DHCPv4 client"; }
              { "udp dport" = 546; comment = "DHCPv6 client"; }
            ];
          };
        };
        masquerade = [
          # Apt-LAN zones egressing to WAN.
          { from = "lan"; to = "wan"; }
          { from = "infra"; to = "wan"; }
          # North-south for everything mdf-agg01 routes. The switch
          # hardware-routes east-west and hands the rest to iyr over the
          # transit link; those packets arrive with the client's source
          # address and still need NAT, which the switch can't do.
          { from = "core-transit"; to = "wan"; }
          # WG-routed traffic to apt zones needs source NAT. The WG
          # cryptokey check at the hub drops sources outside the peer's
          # AllowedIPs; masquerading at iyr makes apt-side traffic look
          # locally-originated so replies come back through iyr.
          { from = "wg"; to = "lan"; }
          { from = "wg"; to = "infra"; }
        ];
      };
    };

    role = "server";

    services = {
      prometheus.collector.enable = true;
      kiosk = {
        enable = true;
        url = "https://metrics.psyclyx.net";
      };
      openbao-seal-oracle = {
        enable = true;
        bindAddress = (eg.entities.${config.networking.hostName}).addresses.infra.ipv4;
        tpm.enable = true;
        seal = {
          type = "pkcs11";
          secretField = "pin";
          lib = "/run/current-system/sw/lib/libtpm2_pkcs11.so";
          slot = "1";
          key_label = "openbao-unseal";
          mechanism = "0x00000009";
          generate_key = "false";
        };
        serviceEnvironment = {
          TPM2_PKCS11_STORE = "/var/lib/openbao-seal/tpm2-pkcs11";
          TPM2_PKCS11_BACKEND = "esysdb";
        };
        pki = {
          enable = true;
          commonName = "psyclyx Internal CA";
          roles = [
            {
              name = "postgres-server";
              allowedDomains = "psyclyx.net";
            }
          ];
        };
      };
    };
  };

}
