{
  imports = [
    ../stylix
    ./hardware/glasgow.nix
    ./hardware/qmk.nix
    ./programs/adb.nix
    ./programs/aspell.nix
    ./programs/steam.nix
    ./programs/sway.nix
    ./programs/zsh.nix
    ./services/automount.nix
    ./roles/graphical.nix
    ./roles/media.nix
    ./roles/remote.nix
    ./roles/utility.nix
    ./services/fwupd.nix
    ./services/gnome-keyring.nix
    ./services/greetd.nix
    ./services/home-assistant.nix
    ./services/kanata
    ./services/locate.nix
    ./services/openrgb.nix
    ./services/openssh.nix
    ./services/printing.nix
    ./services/tailscale.nix
    ./system/console.nix
    ./system/fonts.nix
    ./system/locale.nix
    ./system/nix.nix
    ./system/nixpkgs.nix
    ./system/sudo.nix
    ./system/virtualization.nix
  ];
}
