{ inputs, ... }:
{
  imports = [
    inputs.disko.nixosModules.disko
    ./boot/plymouth.nix
    ./boot/systemd-boot.nix
    ./hardware/cpu
    ./hardware/glasgow.nix
    ./hardware/gpu/intel.nix
    ./hardware/gpu/nvidia.nix
    ./hardware/qmk.nix
    ./hardware/rtl8125.nix
    ./network
    ./programs/adb.nix
    ./programs/aspell.nix
    ./programs/steam.nix
    ./programs/sway.nix
    ./programs/zsh.nix
    ./services/automount.nix
    ./roles/base.nix
    ./roles/graphical.nix
    ./roles/media.nix
    ./roles/remote.nix
    ./roles/utility.nix
    ./services/fstrim.nix
    ./services/fwupd.nix
    ./services/gnome-keyring.nix
    ./services/greetd.nix
    ./services/home-assistant.nix
    ./services/kanata
    ./services/locate.nix
    ./services/openrgb.nix
    ./services/openssh.nix
    ./services/printing.nix
    ./services/tailscale.nix
    ./services/thermald.nix
    ./stylix.nix
    ./system/fonts.nix
    ./system/home-manager.nix
    ./system/locale.nix
    ./system/nix.nix
    ./system/nixpkgs.nix
    ./system/stateVersion.nix
    ./system/sudo.nix
    ./system/timezone.nix
    ./system/virtualization.nix
  ];
}
